### ISSUE TITLE
[feature request] 有可能支持下载Doc或者PDF格式吗

### ISSUE THREAD

**Issue by timelic** [atian25/yuque-exporter#17]
看了一波代码，没找到哪个位置控制下载markdown/doc/pdf文档的。

求一个指导。

**Comment by atian25** [comment]
https://github.com/yuque/yuque-exporter/blob/master/src/lib/crawler.ts#L68

https://github.com/yuque/yuque-exporter/blob/master/src/lib/doc.ts#L94

**Comment by atian25** [comment]
官方 API 没有提供导出 PDF 的，只有 MD，下载 MD 后你再自己用其他库导出 PDF 就好了

**Comment by timelic** [comment]
感谢指点！
