### ISSUE TITLE
问个题外话

### ISSUE THREAD

**Issue by PowerDi** [atian25/yuque-exporter#2]
我想跟随你的脚本，目前迁移出去后续用什么app方案呢？

**Comment by shenweiyan** [comment]
Obsidian 或许是个不错的选择

**Comment by ckvv** [comment]
hugo + github 就够我用了

**Comment by atian25** [comment]
可以发布到 GitHub Pages 或 Obsidian 啥的，反正都是 markdown

**Comment by atian25** [comment]
已正式发布第一个版本
